### PR TITLE
Testing rewriting history

### PR DESCRIPTION
**Pull request by out0xb2**

### CODE REVIEW

**Comment by out0xb2** [comment]
I'm about to rebase...

**Comment by out0xb2** [comment]
See, I tried to hide a commit.  It is hidden in my branch, but you can see it remains in the PR history above.
https://github.com/lersek/edk2/commit/99508025e68e5153603d13e25a50108618997ebc

**Comment by out0xb2** [comment]
I'm going to close, then delete my branch.

**Comment by out0xb2** [comment]
Hmm, it was still here after I deleted the branch, but deleting the repo removed some information above, I had manually captured a link to the commit in my comment, and that commit is still there, but admittedly difficult to find from just this PR view

**Comment by lersek** [comment]
Going back to #1 now, the summary at the top says `out0xb2 wants to merge 1 commit into lersek:master from unknown repository`. Clicking the link to `https://github.com/lersek/edk2/pull/1/commits/364268dc4522ee533f0718ab9c830934fd59d8e3` gives me the original view (from before your deleting of the repo -- subject, commit message, review comments), which is really good.

This raises three more questions:

1. Can I still fetch the original set to a local clone? (Because, that would parallel with a person going back in the email archive to an earlier, unmerged version of the series, and apply it locally. The base commit of that version might not be captured in the email archive, but the date of posting would be a good hint.) Right now I can't even come up with a `git remote add` command, because there is no repo URL to talk of.
2. How long does GitHub preserve the (now possibly orphaned) commit 364268dc4522? For example, GitHub might run a `git gc` (garbage collection) every two weeks, and then the orphaned commits (and their histories) could disappear.
3. If I actually close (reject) #1, will that make a difference, regarding the lifetime of 364268dc4522? In fact I can try closing #1 now.

Thanks!

**Comment by out0xb2** [comment]
Good questions for which I do not have an answer.  Perhaps a web search will reveal.  It seems that the email notifications do not meet your archival goals.  I’m curious if running https://github.com/josegonzalez/python-github-backup daily and stashing somewhere “safe” is an alternative.

________________________________

**Pull request closed without merging**
